format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
